const http = require("http");
const net = require("net");
const fs = require("fs");
const fsp = require("fs").promises;
const path = require("path");
const crypto = require("crypto");
const { spawn, exec } = require("child_process");
const { promisify } = require("util");
const execAsync = promisify(exec);
const pty = require("/app/node_modules/node-pty");
const WebSocket = require("/app/node_modules/ws");

const CONFIG_DIR = process.env.OPENCLAW_DATA_DIR || "/data/.openclaw";
const CONFIG_FILE = path.join(CONFIG_DIR, "openclaw.json");
const ENV_FILE = path.join(CONFIG_DIR, ".env");
const PORT = parseInt(process.env.SETUP_PORT || "18789");
const OPENCLAW_PORT = 18790; // Internal port for OpenClaw gateway
const SKELETON_DIR = "/home-skeleton";
// Anti-CSWSH token for the setup terminal WebSocket. Browsers don't enforce the
// same-origin policy on WebSocket upgrades, so without this any site could connect
// to /api/terminal and hijack the onboarding PTY. We embed APP_SEED (per-user
// secret from umbrelOS) in the served HTML and require it on the WS URL — the
// same-origin policy prevents cross-origin pages from reading it.
const SETUP_TOKEN = process.env.APP_SEED || "";

let openclawProcess = null;
let openclawStarting = false;
let ptyProcess = null;

function readEnv() {
  const env = {};
  try {
    if (fs.existsSync(ENV_FILE)) {
      const content = fs.readFileSync(ENV_FILE, "utf8");
      content.split("\n").forEach((line) => {
        const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
        if (match) {
          env[match[1]] = match[2];
        }
      });
    }
  } catch (e) {
    console.error("Error reading env:", e);
  }
  return env;
}

function writeEnv(env) {
  const lines = ["# OpenClaw Configuration", "# Generated by setup wizard", ""];
  for (const [key, value] of Object.entries(env)) {
    if (value) {
      lines.push(`${key}=${value}`);
    }
  }
  fs.writeFileSync(ENV_FILE, lines.join("\n") + "\n", { mode: 0o600 });
}

function writeConfig(config) {
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2), { mode: 0o600 });
}

function ensureConfigDir() {
  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
  }
  const workspaceDir = path.join(CONFIG_DIR, "workspace");
  if (!fs.existsSync(workspaceDir)) {
    fs.mkdirSync(workspaceDir, { recursive: true });
  }
}

function ensureShellCompletionBypass() {
  const completionDir = path.join(CONFIG_DIR, "completions");
  const completionPath = path.join(completionDir, "openclaw.bash");
  const bashrcPath = path.join(process.env.HOME, ".bashrc");

  fs.mkdirSync(completionDir, { recursive: true });
  if (!fs.existsSync(completionPath)) {
    fs.writeFileSync(completionPath, "# OpenClaw tab-completion disabled in Umbrel.\n");
  }

  let bashrc = "";
  try {
    bashrc = fs.readFileSync(bashrcPath, "utf8");
  } catch {}

  if (!bashrc.includes("# OpenClaw Completion")) {
    // OpenClaw QuickStart auto-generates shell tab-completion when it looks
    // unconfigured. That is not useful in Umbrel's browser terminal and can
    // take ~30s. The marker plus placeholder cache makes OpenClaw skip that
    // setup step without sourcing or executing anything on shell startup.
    const prefix = bashrc && !bashrc.endsWith("\n") ? "\n" : "";
    fs.appendFileSync(bashrcPath, `${prefix}\n# OpenClaw Completion\n`);
  }
}

// Check if a directory is empty
async function isDirEmpty(dirPath) {
  try {
    const entries = await fsp.readdir(dirPath);
    return entries.length === 0;
  } catch {
    return true; // If we can't read it, treat as empty
  }
}

// Copy files from /home-skeleton to $HOME if they don't exist or are empty
async function initializeHome() {
  const homeDir = process.env.HOME;

  try {
    const entries = await fsp.readdir(SKELETON_DIR, { withFileTypes: true });

    for (const entry of entries) {
      const srcPath = path.join(SKELETON_DIR, entry.name);
      const destPath = path.join(homeDir, entry.name);

      try {
        await fsp.access(destPath);
        // Exists - check if it's an empty directory
        if (entry.isDirectory() && (await isDirEmpty(destPath))) {
          console.log(
            `${entry.name} exists but is empty, copying contents inside...`
          );
          await execAsync(`cp -r "${srcPath}/." "${destPath}/"`);
        } else {
          console.log(`Skipping ${entry.name} (already exists)`);
        }
      } catch {
        // Doesn't exist, copy it
        console.log(`Copying ${entry.name} to home...`);
        if (entry.isDirectory()) {
          await execAsync(`cp -r "${srcPath}" "${destPath}"`);
        } else {
          await fsp.copyFile(srcPath, destPath);
        }
      }
    }
    console.log("Home directory initialized");
  } catch (err) {
    console.error("Error initializing home:", err.message);
  }
}

// Config corruption recovery:
// - Mid-run: the gateway keeps its in-memory config and stays up — no action needed.
// - On restart: the gateway tries to boot from the corrupt file and refuses to start.
//   We have two layers of defense:
//   1. readConfig() restores from OpenClaw's native .bak file (covers parse failures).
//   2. runDoctor() runs `openclaw doctor --repair` before gateway start (catches
//      migration issues or structural problems that valid JSON + .bak can't fix).
// - If both .json and .bak are gone/corrupt, readConfig() returns null. isConfigured()
//   falls through to checking .env for API keys. API keys live in a separate file
//   (auth-profiles.json), not in openclaw.json, so they survive config corruption.
//   If auth-profiles.json itself corrupts, the user would need to re-onboard — we
//   intentionally don't cover that edge case to avoid coupling to OpenClaw internals.
function readConfig() {
  try {
    if (fs.existsSync(CONFIG_FILE)) {
      return JSON.parse(fs.readFileSync(CONFIG_FILE, "utf8"));
    }
  } catch (e) {
    console.error("Config file corrupted, attempting restore from backup...");
    const backupFile = CONFIG_FILE + ".bak";
    try {
      if (fs.existsSync(backupFile)) {
        fs.copyFileSync(backupFile, CONFIG_FILE);
        console.log("Restored config from backup");
        return JSON.parse(fs.readFileSync(CONFIG_FILE, "utf8"));
      }
    } catch (e2) {
      console.error("Backup restore also failed:", e2.message);
    }
  }
  return null;
}

function getGatewayToken() {
  const env = readEnv();
  if (env.OPENCLAW_GATEWAY_TOKEN) return env.OPENCLAW_GATEWAY_TOKEN;
  if (process.env.OPENCLAW_GATEWAY_TOKEN) return process.env.OPENCLAW_GATEWAY_TOKEN;
  const config = readConfig();
  if (config && config.gateway && config.gateway.auth && config.gateway.auth.token) {
    return config.gateway.auth.token;
  }
  return null;
}

function isConfigured() {
  // Check if the CLI onboard has been completed (writes wizard section to config)
  const config = readConfig();
  if (config && config.wizard) {
    return true;
  }

  const env = readEnv();
  return !!(
    env.ANTHROPIC_API_KEY ||
    env.OPENAI_API_KEY ||
    env.GEMINI_API_KEY ||
    env.MOONSHOT_API_KEY ||
    env.MINIMAX_API_KEY ||
    env.DASHSCOPE_API_KEY ||
    env.ZAI_API_KEY ||
    env.VENICE_API_KEY ||
    env.XAI_API_KEY ||
    env.GROQ_API_KEY ||
    env.CEREBRAS_API_KEY ||
    env.MISTRAL_API_KEY ||
    env.COPILOT_GITHUB_TOKEN ||
    env.OLLAMA_API_KEY ||
    env.OPENROUTER_API_KEY ||
    process.env.ANTHROPIC_API_KEY ||
    process.env.OPENAI_API_KEY ||
    process.env.GEMINI_API_KEY ||
    process.env.MOONSHOT_API_KEY ||
    process.env.MINIMAX_API_KEY ||
    process.env.DASHSCOPE_API_KEY ||
    process.env.ZAI_API_KEY ||
    process.env.VENICE_API_KEY ||
    process.env.XAI_API_KEY ||
    process.env.GROQ_API_KEY ||
    process.env.CEREBRAS_API_KEY ||
    process.env.MISTRAL_API_KEY ||
    process.env.COPILOT_GITHUB_TOKEN ||
    process.env.OLLAMA_API_KEY ||
    process.env.OPENROUTER_API_KEY
  );
}

function reconcileConfig() {
  const config = readConfig();
  if (!config) return;

  let changed = false;

  // Ensure allowInsecureAuth is set (needed for Umbrel's auth proxy)
  if (!config.gateway) config.gateway = {};
  if (!config.gateway.controlUi) config.gateway.controlUi = {};
  if (!config.gateway.controlUi.allowInsecureAuth) {
    config.gateway.controlUi.allowInsecureAuth = true;
    changed = true;
    console.log("Patched config: enabled allowInsecureAuth");
  }

  // Disable device auth (would break access via umbrel.local)
  if (!config.gateway.controlUi.dangerouslyDisableDeviceAuth) {
    config.gateway.controlUi.dangerouslyDisableDeviceAuth = true;
    changed = true;
    console.log("Patched config: disabled device auth");
  }

  // Disable update checks (updates are managed by Umbrel via Docker image bumps)
  if (!config.update) config.update = {};
  if (config.update.checkOnStart !== false) {
    config.update.checkOnStart = false;
    changed = true;
    console.log("Patched config: disabled update check on start");
  }

  // Ensure a gateway auth token exists — the onboard CLI does not generate one,
  // so without this the Control UI WebSocket fails with "token_missing".
  if (!config.gateway.auth) config.gateway.auth = {};
  if (!config.gateway.auth.token) {
    config.gateway.auth.token = crypto.randomBytes(24).toString("hex");
    changed = true;
    console.log("Patched config: generated gateway auth token");
  }

  // Required since openclaw 2026.3.7 when auth is configured.
  // Always forced to "token" — the proxy only speaks Bearer token auth.
  if (config.gateway.auth.mode !== "token") {
    config.gateway.auth.mode = "token";
    changed = true;
    console.log("Patched config: set gateway auth mode to token");
  }

  if (changed) {
    writeConfig(config);
  }

  // Sync gateway token to .env so the proxy always has it
  const token = config.gateway.auth.token;
  const env = readEnv();
  if (env.OPENCLAW_GATEWAY_TOKEN !== token) {
    env.OPENCLAW_GATEWAY_TOKEN = token;
    writeEnv(env);
    console.log("Synced gateway token to .env");
  }
}

// Run before gateway start to catch migration issues or config problems that
// readConfig()'s backup restore couldn't fix (e.g. schema changes across versions).
async function runDoctor() {
  try {
    await execAsync("openclaw doctor --repair --yes --non-interactive", {
      env: { ...process.env, ...readEnv() },
    });
    console.log("openclaw doctor completed");
  } catch (e) {
    console.error("openclaw doctor failed:", e.message);
  }
}

function startOpenclaw({ repair = true } = {}) {
  // Guard against re-entry: runDoctor() is async, so without this flag every
  // incoming request would see openclawProcess === null and spawn another doctor run.
  if (openclawProcess || openclawStarting) {
    return;
  }

  openclawStarting = true;
  reconcileConfig();

  const spawnGateway = () => {
    openclawStarting = false;
    console.log("Starting OpenClaw gateway...");
    openclawProcess = spawn(
      "openclaw",
      ["gateway", "--port", OPENCLAW_PORT.toString()],
      {
        stdio: "inherit",
        env: {
          ...process.env,
          ...readEnv(),
        },
      }
    );

    openclawProcess.on("exit", (code) => {
      console.log(`OpenClaw exited with code ${code}`);
      openclawProcess = null;
    });
  };

  if (!repair) {
    // Fresh onboarding just wrote this config, so avoid a full repair/migration
    // pass before the first gateway start. We still run doctor on normal
    // already-configured container starts where upgrade or stale-state repairs
    // are plausible.
    console.log("Skipping openclaw doctor after fresh onboarding");
    spawnGateway();
    return;
  }

  // .finally() ensures the gateway starts even if doctor fails or rejects —
  // a degraded gateway is better than no gateway.
  console.log("Running openclaw doctor before gateway start...");
  runDoctor().finally(spawnGateway);
}

// Read static files at startup
const SETUP_HTML = fs.readFileSync(path.join(__dirname, "setup.html"), "utf8");
const LOGO = fs.readFileSync(path.join(__dirname, "logo.webp"));
// Loading page shown while the gateway is starting up.
const LOADING_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<meta name="theme-color" content="#0D0D0D">
<meta name="color-scheme" content="dark">
<meta name="openclaw-loading" content="1">
<title>Starting OpenClaw...</title>
<style>
html,body{margin:0;min-height:100%;background:#0D0D0D;color:#F0EDE8}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Inter,Roboto,sans-serif;display:flex;align-items:center;justify-content:center;padding:max(24px,env(safe-area-inset-top)) max(20px,env(safe-area-inset-right)) max(24px,env(safe-area-inset-bottom)) max(20px,env(safe-area-inset-left));overflow:hidden}
.shell{width:min(100%,420px)}
.card{background:linear-gradient(180deg,rgba(31,31,31,.96),rgba(20,20,20,.98));border:1px solid #2A2A2A;border-radius:20px;padding:24px 20px;box-shadow:0 20px 50px rgba(0,0,0,.45),0 0 0 1px rgba(255,90,45,.06);text-align:center}
.logo{width:72px;height:72px;display:block;margin:0 auto 18px;object-fit:contain}
h1{margin:0 0 10px;font-size:clamp(24px,5vw,30px);line-height:1.15}
p{margin:0;color:#A89F99;font-size:15px;line-height:1.6}
.status{margin-top:20px;display:inline-flex;align-items:center;gap:10px;padding:10px 14px;border-radius:999px;background:#141414;border:1px solid #2A2A2A;color:#D4D0CB;font-size:14px}
.spinner{width:16px;height:16px;border:2px solid rgba(240,237,232,.18);border-top-color:#FF5A2D;border-radius:999px;animation:spin .85s linear infinite}
.progress{margin-top:18px;height:6px;border-radius:999px;background:#141414;overflow:hidden;border:1px solid #252525}
.progress::before{content:"";display:block;width:42%;height:100%;border-radius:999px;background:linear-gradient(90deg,#FF5A2D,#FF8A65);animation:slide 1.4s ease-in-out infinite}
.hint{margin-top:14px;font-size:12px;color:#6B6460}
@keyframes spin{to{transform:rotate(360deg)}}
@keyframes slide{0%{transform:translateX(-120%)}60%{transform:translateX(170%)}100%{transform:translateX(170%)}}
@media (max-width:480px){.card{padding:22px 16px;border-radius:18px}.logo{width:64px;height:64px;margin-bottom:16px}p{font-size:14px}.status{width:100%;justify-content:center;box-sizing:border-box}}
</style>
</head>
<body>
<div class="shell">
<div class="card">
<img class="logo" src="/logo.webp" alt="OpenClaw">
<h1>Starting OpenClaw</h1>
<p>Please wait while the gateway finishes booting. You’ll be redirected automatically as soon as it’s ready.</p>
<div class="status"><span class="spinner"></span><span id="status-text">Checking availability…</span></div>
<div class="progress"></div>
<div class="hint">This usually only takes a moment.</div>
</div>
</div>
<script>
(()=>{
const statusText=document.getElementById('status-text');
const marker='name="openclaw-loading"';
let attempts=0;
async function checkReady(){
  attempts+=1;
  try{
    const response=await fetch(location.href.split('#')[0],{cache:'no-store',credentials:'same-origin'});
    const text=await response.text();
    if(!text.includes(marker)){
      location.reload();
      return;
    }
    statusText.textContent=attempts>3?'Still starting…':'Checking availability…';
  }catch(_error){
    statusText.textContent='Still starting…';
  }
  setTimeout(checkReady,1200);
}
setTimeout(checkReady,900);
})();
</script>
</body>
</html>`;

function proxyToOpenclaw(req, res) {
  const token = getGatewayToken();

  // Redirect root to a tokenized URL so the Control UI can authenticate.
  // The token goes in two places:
  //   ?token=… — prevents a redirect loop (server checks searchParams)
  //   #token=… — delivers the token to the Control UI JS, which reads auth
  //              exclusively from the hash fragment, not query params
  const url = new URL(req.url, `http://${req.headers.host}`);
  if (token && url.pathname === "/" && url.searchParams.get("token") !== token) {
    // If setup generated or repaired a token while the browser still has an
    // older dashboard URL, force the URL hash back in sync. The Control UI reads
    // auth from the hash, so a stale token there causes WebSocket auth failures
    // even though the proxy injects the current Bearer token.
    const encodedToken = encodeURIComponent(token);
    res.writeHead(302, { Location: `/?token=${encodedToken}#token=${encodedToken}` });
    res.end();
    return;
  }

  // Rewrite headers so the gateway sees requests as local.
  // The gateway checks Origin/Host to block cross-origin requests (anti-CSRF),
  // but that's redundant here — our proxy is the only thing that can reach the
  // gateway (it binds to 127.0.0.1 inside the container), and on Umbrel the
  // entire app is already behind Umbrel's auth proxy.
  // We also strip forwarding headers (X-Forwarded-For, etc.) that Umbrel's
  // reverse proxy injects — if the gateway sees these from a source not in
  // gateway.trustedProxies it treats the connection as non-local and rejects it.
  const gatewayHost = `127.0.0.1:${OPENCLAW_PORT}`;
  const headers = { ...req.headers };
  headers["host"] = gatewayHost;
  headers["origin"] = `http://${gatewayHost}`;
  delete headers["x-forwarded-for"];
  delete headers["x-forwarded-proto"];
  delete headers["x-forwarded-host"];
  delete headers["x-forwarded-port"];
  delete headers["x-real-ip"];
  delete headers["forwarded"];
  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }

  const options = {
    hostname: "127.0.0.1",
    port: OPENCLAW_PORT,
    path: req.url,
    method: req.method,
    headers: headers,
  };

  const proxy = http.request(options, (proxyRes) => {
    res.writeHead(proxyRes.statusCode, proxyRes.headers);
    proxyRes.pipe(res);
  });

  proxy.on("error", () => {
    // OpenClaw not ready yet, show loading page
    res.writeHead(200, { "Content-Type": "text/html", "Cache-Control": "no-store" });
    res.end(LOADING_HTML);
  });

  req.pipe(proxy);
}

// Handle WebSocket upgrade requests
function handleUpgrade(req, socket, head) {
  const token = getGatewayToken();

  // Connect to OpenClaw gateway
  const proxySocket = net.connect(OPENCLAW_PORT, "127.0.0.1", () => {
    // Rebuild the upgrade request with auth header
    let requestLine = `${req.method} ${req.url} HTTP/1.1\r\n`;

    // Rewrite headers to appear local (same rationale as HTTP proxy above)
    const gatewayHost = `127.0.0.1:${OPENCLAW_PORT}`;
    const headers = { ...req.headers };
    headers["host"] = gatewayHost;
    headers["origin"] = `http://${gatewayHost}`;
    delete headers["x-forwarded-for"];
    delete headers["x-forwarded-proto"];
    delete headers["x-forwarded-host"];
    delete headers["x-forwarded-port"];
    delete headers["x-real-ip"];
    delete headers["forwarded"];
    if (token) {
      headers["authorization"] = `Bearer ${token}`;
    }

    let headerLines = "";
    for (const [key, value] of Object.entries(headers)) {
      if (Array.isArray(value)) {
        value.forEach((v) => (headerLines += `${key}: ${v}\r\n`));
      } else {
        headerLines += `${key}: ${value}\r\n`;
      }
    }

    // Send the upgrade request to OpenClaw
    proxySocket.write(requestLine + headerLines + "\r\n");
    if (head && head.length) {
      proxySocket.write(head);
    }

    // Pipe data between client and OpenClaw
    socket.pipe(proxySocket);
    proxySocket.pipe(socket);
  });

  proxySocket.on("error", (err) => {
    console.error("WebSocket proxy error:", err.message);
    socket.end();
  });

  socket.on("error", (err) => {
    console.error("Client socket error:", err.message);
    proxySocket.end();
  });

  socket.on("close", () => {
    proxySocket.end();
  });

  proxySocket.on("close", () => {
    socket.end();
  });
}

const server = http.createServer((req, res) => {
  // Serve static assets for setup UI
  if (req.url === "/logo.webp") {
    res.writeHead(200, { "Content-Type": "image/webp", "Cache-Control": "public, max-age=86400" });
    res.end(LOGO);
    return;
  }

  if (!isConfigured()) {
    if (req.url !== "/") {
      res.writeHead(302, { Location: "/" });
      res.end();
      return;
    }
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end(SETUP_HTML.replace("__SETUP_TOKEN__", SETUP_TOKEN));
    return;
  }

  if (ptyProcess) {
    // OpenClaw writes config before QuickStart fully exits. Keep the browser on
    // the terminal until onboarding is done so the gateway never starts against
    // config/auth files that OpenClaw may still rewrite.
    if (req.url !== "/") {
      res.writeHead(302, { Location: "/" });
      res.end();
      return;
    }
    res.writeHead(200, { "Content-Type": "text/html" });
    res.end(SETUP_HTML.replace("__SETUP_TOKEN__", SETUP_TOKEN));
    return;
  }

  // If configured but OpenClaw not running, start it
  if (!openclawProcess) {
    startOpenclaw();
  }

  // Proxy to OpenClaw
  proxyToOpenclaw(req, res);
});

// WebSocket server for the interactive terminal
const wss = new WebSocket.Server({ noServer: true });

wss.on("connection", (ws) => {
  console.log("Terminal WebSocket connected");

  // Only one setup session at a time — kill any existing PTY (e.g. stale tab)
  if (ptyProcess) {
    try { ptyProcess.kill(); } catch (e) {}
    ptyProcess = null;
  }

  // Spawn openclaw onboard with flags that skip everything except provider/API key selection.
  // The CLI does NOT generate a gateway token — reconcileConfig() generates one and
  // syncs it to .env when startOpenclaw() runs after setup.
  ensureConfigDir();
  ensureShellCompletionBypass();
  ptyProcess = pty.spawn("openclaw", [
    "onboard",
    "--flow", "quickstart",
    "--accept-risk",
    "--skip-channels",
    "--skip-skills",
    "--skip-search",
    "--skip-daemon",
    "--skip-ui",
    "--skip-health",
    "--mode", "local",
    "--gateway-port", OPENCLAW_PORT.toString(),
  ], {
    name: "xterm-256color",
    cols: 80,
    rows: 24,
    cwd: CONFIG_DIR,
    env: {
      ...process.env,
      ...readEnv(),
      SHELL: "/bin/bash",
      TERM: "xterm-256color",
    },
  });

  // PTY output -> WebSocket
  ptyProcess.onData((data) => {
    try {
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify({ type: "output", data }));
      }
    } catch (e) {
      console.error("Error sending PTY output:", e.message);
    }
  });

  // PTY exit -> notify client
  ptyProcess.onExit(({ exitCode }) => {
    console.log(`openclaw onboard exited with code ${exitCode}`);
    try {
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify({ type: "exit", code: exitCode }));
      }
    } catch (e) {
      console.error("Error sending exit message:", e.message);
    }
    ptyProcess = null;

    if (exitCode === 0 && isConfigured() && !openclawProcess) {
      console.log("OpenClaw onboarding completed, starting gateway...");
      startOpenclaw({ repair: false });
    }
  });

  // WebSocket input -> PTY
  ws.on("message", (msg) => {
    try {
      const parsed = JSON.parse(msg);
      if (parsed.type === "input" && ptyProcess) {
        ptyProcess.write(parsed.data);
      } else if (parsed.type === "resize" && ptyProcess) {
        ptyProcess.resize(parsed.cols, parsed.rows);
      }
    } catch (e) {
      console.error("Error processing terminal input:", e.message);
    }
  });

  ws.on("close", () => {
    console.log("Terminal WebSocket closed");
    if (ptyProcess) {
      try { ptyProcess.kill(); } catch (e) {}
      ptyProcess = null;
    }
  });
});

// Handle WebSocket upgrades
server.on("upgrade", (req, socket, head) => {
  const url = new URL(req.url, `http://${req.headers.host}`);

  // Route /api/terminal to the PTY WebSocket server
  if (url.pathname === "/api/terminal") {
    // Validate anti-CSWSH token (see SETUP_TOKEN comment above)
    const provided = url.searchParams.get("token") || "";
    if (!SETUP_TOKEN || provided.length !== SETUP_TOKEN.length ||
        !crypto.timingSafeEqual(Buffer.from(provided), Buffer.from(SETUP_TOKEN))) {
      socket.write("HTTP/1.1 403 Forbidden\r\n\r\n");
      socket.destroy();
      return;
    }
    wss.handleUpgrade(req, socket, head, (ws) => {
      wss.emit("connection", ws, req);
    });
    return;
  }

  if (!isConfigured()) {
    socket.end("HTTP/1.1 503 Service Unavailable\r\n\r\n");
    return;
  }

  if (ptyProcess) {
    socket.end("HTTP/1.1 503 Service Unavailable\r\n\r\n");
    return;
  }

  if (!openclawProcess) {
    startOpenclaw();
  }

  handleUpgrade(req, socket, head);
});

// Initialize home directory from skeleton
initializeHome();

ensureConfigDir();

// Check if already configured
if (isConfigured()) {
  console.log("OpenClaw is configured, starting gateway...");
  startOpenclaw();
} else {
  console.log("OpenClaw not configured, showing setup UI...");
}

server.listen(PORT, "0.0.0.0", () => {
  console.log(`Setup server listening on port ${PORT}`);
});

// Graceful shutdown: Docker sends SIGTERM on stop/restart/update.
// Without this, child processes (gateway, PTY) may get hard-killed
// mid-write and corrupt config or state files.
process.on("SIGTERM", () => {
  console.log("Received SIGTERM, shutting down...");
  if (ptyProcess) {
    try { ptyProcess.kill(); } catch (e) {}
  }
  if (openclawProcess) {
    openclawProcess.kill("SIGTERM");
  }
  server.close();
});
