const http = require('http');
const net = require('net');
const fs = require('fs');
const fsp = require('fs').promises;
const path = require('path');
const { spawn, exec } = require('child_process');
const { promisify } = require('util');
const execAsync = promisify(exec);

const CONFIG_DIR = process.env.OPENCLAW_DATA_DIR || '/data/.openclaw';
const CONFIG_FILE = path.join(CONFIG_DIR, 'openclaw.json');
const ENV_FILE = path.join(CONFIG_DIR, '.env');
const PORT = parseInt(process.env.SETUP_PORT || '18789');
const OPENCLAW_PORT = 18790; // Internal port for OpenClaw gateway

let openclawProcess = null;

function readConfig() {
  try {
    if (fs.existsSync(CONFIG_FILE)) {
      return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'));
    }
  } catch (e) {
    console.error('Error reading config:', e);
  }
  return null;
}

function readEnv() {
  const env = {};
  try {
    if (fs.existsSync(ENV_FILE)) {
      const content = fs.readFileSync(ENV_FILE, 'utf8');
      content.split('\n').forEach(line => {
        const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
        if (match) {
          env[match[1]] = match[2];
        }
      });
    }
  } catch (e) {
    console.error('Error reading env:', e);
  }
  return env;
}

function writeEnv(env) {
  const lines = ['# OpenClaw Configuration', '# Generated by setup wizard', ''];
  for (const [key, value] of Object.entries(env)) {
    if (value) {
      lines.push(`${key}=${value}`);
    }
  }
  fs.writeFileSync(ENV_FILE, lines.join('\n') + '\n');
}

function writeConfig(config) {
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2));
}

function ensureConfigDir() {
  if (!fs.existsSync(CONFIG_DIR)) {
    fs.mkdirSync(CONFIG_DIR, { recursive: true });
  }
  const workspaceDir = path.join(CONFIG_DIR, 'workspace');
  if (!fs.existsSync(workspaceDir)) {
    fs.mkdirSync(workspaceDir, { recursive: true });
  }
}

async function ensureHomebrew(attempt = 1) {
  const maxAttempts = 5;
  const brewPath = path.join(process.env.HOME, '.linuxbrew', 'bin', 'brew');

  try {
    await fsp.access(brewPath);
    console.log('Homebrew already installed');
    return;
  } catch {
    // brew not found, continue with install
  }

  console.log(`Installing Homebrew to persistent volume (attempt ${attempt}/${maxAttempts})...`);
  const homebrewDir = path.join(process.env.HOME, '.linuxbrew');
  const repoDir = path.join(homebrewDir, 'Homebrew');

  try {
    // Clean up any partial install
    await fsp.rm(homebrewDir, { recursive: true, force: true }).catch(() => {});

    await fsp.mkdir(homebrewDir, { recursive: true });
    console.log('Cloning Homebrew repository...');
    await execAsync(`git clone --depth=1 https://github.com/Homebrew/brew ${repoDir}`);
    await fsp.mkdir(path.join(homebrewDir, 'bin'), { recursive: true });
    await fsp.symlink(path.join(repoDir, 'bin', 'brew'), path.join(homebrewDir, 'bin', 'brew'));
    console.log('Running brew update...');
    await execAsync(`${brewPath} update --force`);
    console.log('Homebrew installed successfully');
  } catch (err) {
    console.error('Failed to install Homebrew:', err.message);
    if (attempt < maxAttempts) {
      const delay = Math.pow(2, attempt) * 1000; // Exponential backoff
      console.log(`Retrying in ${delay / 1000} seconds...`);
      setTimeout(() => ensureHomebrew(attempt + 1), delay);
    } else {
      console.error('Max attempts reached, Homebrew installation failed');
    }
  }
}

function isConfigured() {
  const env = readEnv();
  return !!(env.ANTHROPIC_API_KEY || env.OPENAI_API_KEY || process.env.ANTHROPIC_API_KEY || process.env.OPENAI_API_KEY);
}

function startOpenclaw() {
  if (openclawProcess) {
    console.log('OpenClaw already running');
    return;
  }

  console.log('Starting OpenClaw gateway...');
  openclawProcess = spawn('openclaw', [
    'gateway',
    '--port', OPENCLAW_PORT.toString()
  ], {
    stdio: 'inherit',
    env: {
      ...process.env,
      ...readEnv()
    }
  });

  openclawProcess.on('exit', (code) => {
    console.log(`OpenClaw exited with code ${code}`);
    openclawProcess = null;
  });
}

function getSetupHtml() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>OpenClaw Setup</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 20px;
    }
    .container {
      background: #fff;
      border-radius: 16px;
      padding: 40px;
      max-width: 500px;
      width: 100%;
      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
    }
    h1 {
      font-size: 28px;
      margin-bottom: 8px;
      color: #1a1a2e;
    }
    .subtitle {
      color: #666;
      margin-bottom: 32px;
    }
    .form-group {
      margin-bottom: 24px;
    }
    label {
      display: block;
      font-weight: 600;
      margin-bottom: 8px;
      color: #333;
    }
    input[type="password"], input[type="text"], select {
      width: 100%;
      padding: 12px 16px;
      border: 2px solid #e0e0e0;
      border-radius: 8px;
      font-size: 16px;
      transition: border-color 0.2s;
    }
    input:focus, select:focus {
      outline: none;
      border-color: #6366f1;
    }
    .help-text {
      font-size: 13px;
      color: #666;
      margin-top: 6px;
    }
    .help-text a {
      color: #6366f1;
    }
    button {
      width: 100%;
      padding: 14px;
      background: #6366f1;
      color: white;
      border: none;
      border-radius: 8px;
      font-size: 16px;
      font-weight: 600;
      cursor: pointer;
      transition: background 0.2s;
    }
    button:hover {
      background: #4f46e5;
    }
    button:disabled {
      background: #ccc;
      cursor: not-allowed;
    }
    .error {
      background: #fee2e2;
      color: #dc2626;
      padding: 12px;
      border-radius: 8px;
      margin-bottom: 24px;
      display: none;
    }
    .success {
      background: #d1fae5;
      color: #059669;
      padding: 12px;
      border-radius: 8px;
      margin-bottom: 24px;
      display: none;
    }
    .divider {
      text-align: center;
      color: #999;
      margin: 20px 0;
      position: relative;
    }
    .divider::before, .divider::after {
      content: '';
      position: absolute;
      top: 50%;
      width: 40%;
      height: 1px;
      background: #e0e0e0;
    }
    .divider::before { left: 0; }
    .divider::after { right: 0; }
    .optional-section {
      background: #f8fafc;
      padding: 20px;
      border-radius: 8px;
      margin-top: 24px;
    }
    .optional-section h3 {
      font-size: 16px;
      margin-bottom: 16px;
      color: #475569;
    }
    .toggle-optional {
      background: none;
      border: 1px solid #e0e0e0;
      color: #666;
      margin-top: 16px;
    }
    .toggle-optional:hover {
      background: #f0f0f0;
      border-color: #ccc;
    }
    .hidden { display: none; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Welcome to OpenClaw</h1>
    <p class="subtitle">Your personal AI assistant. Let's get you set up.</p>

    <div id="error" class="error"></div>
    <div id="success" class="success"></div>

    <form id="setup-form">
      <div class="form-group">
        <label for="provider">AI Provider</label>
        <select id="provider" name="provider">
          <option value="anthropic">Anthropic (Claude)</option>
          <option value="openai">OpenAI (GPT)</option>
        </select>
      </div>

      <div class="form-group">
        <label for="api-key">API Key</label>
        <input type="password" id="api-key" name="api-key" placeholder="sk-..." required>
        <p class="help-text" id="api-help">
          Get your API key from <a href="https://console.anthropic.com/" target="_blank">console.anthropic.com</a>
        </p>
      </div>

      <div class="form-group">
        <label for="model">Model</label>
        <select id="model" name="model">
          <option value="sonnet">Claude Sonnet (Recommended)</option>
          <option value="opus">Claude Opus</option>
        </select>
      </div>

      <button type="submit" id="submit-btn">Start OpenClaw</button>

      <button type="button" class="toggle-optional" onclick="toggleOptional()">
        Show Optional Settings
      </button>

      <div id="optional-section" class="optional-section hidden">
        <h3>Optional: Messaging Integrations</h3>

        <div class="form-group">
          <label for="telegram-token">Telegram Bot Token</label>
          <input type="password" id="telegram-token" name="telegram-token" placeholder="123456:ABC-DEF...">
          <p class="help-text">Create a bot via @BotFather on Telegram</p>
        </div>

        <div class="form-group">
          <label for="discord-token">Discord Bot Token</label>
          <input type="password" id="discord-token" name="discord-token" placeholder="MTIz...">
          <p class="help-text">Create at <a href="https://discord.com/developers/applications" target="_blank">discord.com/developers</a></p>
        </div>
      </div>
    </form>
  </div>

  <script>
    const providerSelect = document.getElementById('provider');
    const modelSelect = document.getElementById('model');
    const apiHelp = document.getElementById('api-help');

    const models = {
      anthropic: [
        { value: 'sonnet', label: 'Claude Sonnet (Recommended)' },
        { value: 'opus', label: 'Claude Opus' }
      ],
      openai: [
        { value: 'gpt', label: 'GPT-4o (Recommended)' },
        { value: 'openai/gpt-4-turbo', label: 'GPT-4 Turbo' }
      ]
    };

    const helpLinks = {
      anthropic: 'Get your API key from <a href="https://console.anthropic.com/" target="_blank">console.anthropic.com</a>',
      openai: 'Get your API key from <a href="https://platform.openai.com/api-keys" target="_blank">platform.openai.com</a>'
    };

    providerSelect.addEventListener('change', () => {
      const provider = providerSelect.value;
      modelSelect.innerHTML = models[provider]
        .map(m => \`<option value="\${m.value}">\${m.label}</option>\`)
        .join('');
      apiHelp.innerHTML = helpLinks[provider];
    });

    function toggleOptional() {
      const section = document.getElementById('optional-section');
      const btn = document.querySelector('.toggle-optional');
      section.classList.toggle('hidden');
      btn.textContent = section.classList.contains('hidden')
        ? 'Show Optional Settings'
        : 'Hide Optional Settings';
    }

    document.getElementById('setup-form').addEventListener('submit', async (e) => {
      e.preventDefault();

      const btn = document.getElementById('submit-btn');
      const error = document.getElementById('error');
      const success = document.getElementById('success');

      btn.disabled = true;
      btn.textContent = 'Setting up...';
      error.style.display = 'none';
      success.style.display = 'none';

      const data = {
        provider: providerSelect.value,
        apiKey: document.getElementById('api-key').value,
        model: modelSelect.value,
        telegramToken: document.getElementById('telegram-token').value,
        discordToken: document.getElementById('discord-token').value
      };

      try {
        const res = await fetch('/api/setup', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(data)
        });

        const result = await res.json();

        if (result.success) {
          success.textContent = 'Configuration saved! Starting OpenClaw...';
          success.style.display = 'block';
          setTimeout(() => {
            window.location.reload();
          }, 3000);
        } else {
          throw new Error(result.error || 'Setup failed');
        }
      } catch (err) {
        error.textContent = err.message;
        error.style.display = 'block';
        btn.disabled = false;
        btn.textContent = 'Start OpenClaw';
      }
    });
  </script>
</body>
</html>`;
}

function handleApiSetup(req, res) {
  let body = '';
  req.on('data', chunk => body += chunk);
  req.on('end', () => {
    try {
      const data = JSON.parse(body);

      ensureConfigDir();

      // Build environment variables
      const env = readEnv();
      if (data.provider === 'anthropic') {
        env.ANTHROPIC_API_KEY = data.apiKey;
      } else {
        env.OPENAI_API_KEY = data.apiKey;
      }
      if (data.telegramToken) env.TELEGRAM_BOT_TOKEN = data.telegramToken;
      if (data.discordToken) env.DISCORD_BOT_TOKEN = data.discordToken;

      // Fixed token - safe behind Umbrel's auth proxy
      const gatewayToken = 'openclaw-umbrel-token';

      // Also save token to env for the proxy to use
      env.OPENCLAW_GATEWAY_TOKEN = gatewayToken;

      writeEnv(env);

      // Build minimal valid config
      const config = {
        agents: {
          defaults: {
            model: {
              primary: data.model
            }
          }
        },
        gateway: {
          mode: 'local',
          auth: {
            token: gatewayToken
          }
        }
      };

      writeConfig(config);

      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ success: true }));

      // Start OpenClaw after a short delay
      setTimeout(() => {
        console.log('Configuration complete, starting OpenClaw...');
        startOpenclaw();
      }, 1000);

    } catch (err) {
      console.error('Setup error:', err);
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ success: false, error: err.message }));
    }
  });
}

function proxyToOpenclaw(req, res) {
  const env = readEnv();
  const token = env.OPENCLAW_GATEWAY_TOKEN || process.env.OPENCLAW_GATEWAY_TOKEN;

  // For the root path, redirect to include token if not present
  const url = new URL(req.url, `http://${req.headers.host}`);
  if (token && req.url === '/' && !url.searchParams.has('token')) {
    res.writeHead(302, { 'Location': `/?token=${token}` });
    res.end();
    return;
  }

  const headers = { ...req.headers };
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
  }

  const options = {
    hostname: '127.0.0.1',
    port: OPENCLAW_PORT,
    path: req.url,
    method: req.method,
    headers: headers
  };

  const proxy = http.request(options, (proxyRes) => {
    res.writeHead(proxyRes.statusCode, proxyRes.headers);
    proxyRes.pipe(res);
  });

  proxy.on('error', () => {
    // OpenClaw not ready yet, show loading page
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(`<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Starting...</title>
<meta http-equiv="refresh" content="2">
<style>body{font-family:sans-serif;display:flex;align-items:center;justify-content:center;height:100vh;background:#1a1a2e;color:#fff;}</style>
</head><body><div><h1>Starting OpenClaw...</h1><p>Please wait, this may take a moment.</p></div></body></html>`);
  });

  req.pipe(proxy);
}

// Handle WebSocket upgrade requests
function handleUpgrade(req, socket, head) {
  const env = readEnv();
  const token = env.OPENCLAW_GATEWAY_TOKEN || process.env.OPENCLAW_GATEWAY_TOKEN;

  // Connect to OpenClaw gateway
  const proxySocket = net.connect(OPENCLAW_PORT, '127.0.0.1', () => {
    // Rebuild the upgrade request with auth header
    let requestLine = `${req.method} ${req.url} HTTP/1.1\r\n`;

    // Copy headers and add auth
    const headers = { ...req.headers };
    if (token) {
      headers['authorization'] = `Bearer ${token}`;
    }

    let headerLines = '';
    for (const [key, value] of Object.entries(headers)) {
      if (Array.isArray(value)) {
        value.forEach(v => headerLines += `${key}: ${v}\r\n`);
      } else {
        headerLines += `${key}: ${value}\r\n`;
      }
    }

    // Send the upgrade request to OpenClaw
    proxySocket.write(requestLine + headerLines + '\r\n');
    if (head && head.length) {
      proxySocket.write(head);
    }

    // Pipe data between client and OpenClaw
    socket.pipe(proxySocket);
    proxySocket.pipe(socket);
  });

  proxySocket.on('error', (err) => {
    console.error('WebSocket proxy error:', err.message);
    socket.end();
  });

  socket.on('error', (err) => {
    console.error('Client socket error:', err.message);
    proxySocket.end();
  });

  socket.on('close', () => {
    proxySocket.end();
  });

  proxySocket.on('close', () => {
    socket.end();
  });
}

const server = http.createServer((req, res) => {
  // API endpoint for setup
  if (req.method === 'POST' && req.url === '/api/setup') {
    return handleApiSetup(req, res);
  }

  // If not configured, show setup UI
  if (!isConfigured()) {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(getSetupHtml());
    return;
  }

  // If configured but OpenClaw not running, start it
  if (!openclawProcess) {
    startOpenclaw();
  }

  // Proxy to OpenClaw
  proxyToOpenclaw(req, res);
});

// Handle WebSocket upgrades
server.on('upgrade', (req, socket, head) => {
  if (!isConfigured()) {
    socket.end('HTTP/1.1 503 Service Unavailable\r\n\r\n');
    return;
  }

  if (!openclawProcess) {
    startOpenclaw();
  }

  handleUpgrade(req, socket, head);
});

ensureConfigDir();
ensureHomebrew(); // Runs in background (async)

// Check if already configured
if (isConfigured()) {
  console.log('OpenClaw is configured, starting gateway...');
  startOpenclaw();
} else {
  console.log('OpenClaw not configured, showing setup UI...');
}

server.listen(PORT, '0.0.0.0', () => {
  console.log(`Setup server listening on port ${PORT}`);
});
